server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
#      TODO: this doesn't work
      - local.host/prometheus
#      TODO: this works though
      - prom.localhost

